### PR TITLE
feat: add custom marshaler and fix go mods for examples

### LINKED ISSUE #6: Add Custom Response Marshaler
currently, there is not good way to pass bytes directly to the response writer using GLHF. 

It would be worth adding a customer marshaler that can be user supplied if the default marshalers do not support the format.

### PR DESCRIPTION
**Pull request by elewis787**
closes #6

### CODE REVIEW

File: response.go [hunk 1]
```diff
@@ -25,11 +26,22 @@ func (res *Response[T]) AddHeader(k string, v string) {
...
+		res.statusCode = statusCode
+	}
 }
 
+// SetBody sets the response body
 func (res *Response[T]) SetBody(t *T) {
 	res.body = t
 }
+
+// SetMarshalFunc sets the response marhsal func. If a marsharl function is supplied, it is prioritized over
```
Comment (jeff1010322) [inline response.go:43]: marshal misspelled here a couple times.

**Comment by elewis787** [comment]
I will be working on #8 before merging this as well.

**Review by jeff1010322 — APPROVED** [review]
LGTM!
